stages:
  - build
  - publish
  - deploy-staging
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  SSH_CONFIG: "-o StrictHostKeyChecking=no"

build_and_test:
  stage: build
  image: registry.gitlab.com/aelve/codesearch/ci-test-env
  services:
    - docker:dind
  script:
    - sbt compile
    - sbt core/assembly
    - sbt web-server/assembly
    - sbt scalafmt exit
    - git diff --exit-code
  artifacts:
    paths:
      - target/resolution-cache
      - target/streams
      - project/target/resolution-cache
      - project/target/streams
      - ~/.sbt
      - ~/.iv2/cache
      - ~/.m2
      - .dockerignore
      - docker
      - scripts
      - Makefile
      - codesearch-core.jar
      - codesearch-server.jar

build_and_publish_docker_images:
  stage: publish
  image: registry.gitlab.com/aelve/codesearch/ci-test-env
  services:
    - docker:dind
  before_script:
    - docker login quay.io -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - make build-docker-core "branch=${CI_COMMIT_REF_NAME}"
    - make build-docker-web-server "branch=${CI_COMMIT_REF_NAME}"
    - make push-docker-core "branch=${CI_COMMIT_REF_NAME}"
    - make push-docker-web-server "branch=${CI_COMMIT_REF_NAME}"
  only:
    - develop
    - master
    - hotfix-fixed-bug-with-gitlabci

staging-deploy-to-swarm:
  stage: deploy-staging
  script:
    - ssh deployer@$STAGING_HOST "mkdir -p ~/docker && echo $DEPLOYER_PASS | sudo -S mkdir -p /mnt/vol/{portainer/data,postgresql,data,index,logs}" || true
    - scp ./docker/docker-stack-compose.yml deployer@$STAGING_HOST:~/docker
    - ssh deployer@$STAGING_HOST "docker login quay.io -u $DOCKER_USER -p $DOCKER_PASS" || true
    - ssh deployer@$STAGING_HOST "SECRET_KEY=$STAGING_SECRET_KEY SERVER_PORT=$SERVER_PORT docker stack deploy --with-registry-auth -c ~/docker/docker-stack-compose.yml codesearch" || true
  only:
    - develop

deploy-to-swarm:
  stage: deploy
  script:
    - ssh deployer@$HOST "mkdir -p ~/docker && echo $DEPLOYER_PASS | sudo -S mkdir -p /mnt/vol/{portainer/data,postgresql,data,index,logs}" || true
    - scp ./docker/docker-stack-compose.yml deployer@$HOST:~/docker
    - ssh deployer@$HOST "docker login quay.io -u $DOCKER_USER -p $DOCKER_PASS" || true
    - ssh deployer@$HOST "SECRET_KEY=$SECRET_KEY SERVER_PORT=$SERVER_PORT docker stack deploy --with-registry-auth -c ~/docker/docker-stack-compose.yml codesearch" || true
  only:
    - master