stages:
  - build
  - publish

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build_and_test:
  stage: build
  image: registry.gitlab.com/aelve/codesearch/ci-test-env
  services:
    - docker:dind
  script:
    - sbt compile
    - sbt core/assembly
    - sbt web-server/assembly
    - sbt scalafmt exit
    - git diff --exit-code
  artifacts:
    paths:
      - target/resolution-cache
      - target/streams
      - project/target/resolution-cache
      - project/target/streams
      - ~/.sbt
      - ~/.iv2/cache
      - ~/.m2
      - .dockerignore
      - docker
      - scripts
      - Makefile
      - codesearch-core.jar
      - codesearch-server.jar


build_and_publish_docker_images:
  stage: publish
  image: registry.gitlab.com/aelve/codesearch/ci-test-env
  services:
    - docker:dind
  script:
    - make build-docker-core
    - make build-docker-web-server
    - make push-docker-core
    - make push-docker-web-server
  only:
    - develop
    - master