version: '3.3'

services:
  portainer:
    image: portainer/portainer:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/vol/portainer/data:/data
    ports:
      - 9080:9000
    networks:
      - overlay
  postgres:
    image: postgres:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
    volumes:
      - /mnt/vol/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sourcesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - overlay
  core:
    image: quay.io/aelve/codesearch-core:develop
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5h
      update_config:
        failure_action: rollback
    depends_on:
      - postgres
    volumes:
      - /mnt/vol/data:/data
      - /mnt/vol/index:/index
      - /mnt/vol/logs:/logs
    command: >
      sh -c "./wait-for postgres:5432 -- make tables && \
            make download-haskell update-haskell index-haskell && \
            make download-rust update-rust index-rust"
    networks:
      - overlay
  server:
    image: quay.io/aelve/codesearch-web-server:develop
    deploy:
      mode: global
      restart_policy:
        condition: any
      update_config:
        failure_action: rollback
    volumes:
      - /mnt/vol/data:/data
      - /mnt/vol/index:/index
    depends_on:
      - postgres
    command:
      make serve
    environment:
      LOG_LEVEL: DEBUG
      JAVA_OPTS: "-Dplay.filters.hosts.allowed.1=staging.codesearch.aelve.com -Dplay.filters.hosts.allowed.2=cloud.digitalocean.com"
      # In production you must override the APPLICATION_SECRET key
      APPLICATION_SECRET: ${SECRET_KEY:-"u?:IPZT:Cun;SP>edigHDs:cpUf2cY\`<7D>b9lHg98^NsVGn]:eLCIjz1Tt_VyIv"}
    ports:
      # In production you must override SERVER_PORT like: `SERVER_PORT=80 docker-compose -f docker-stack-compose.yml ...`
      - ${SERVER_PORT:-9000}:80
    networks:
      - overlay
networks:
  overlay: