version: '3.3'

services:
  portainer:
    image: portainer/portainer:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/vol/portainer/data:/data
    ports:
      - 9080:9000
    networks:
      - overlay
  postgres:
    image: postgres:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
    volumes:
      - /mnt/vol/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sourcesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - overlay
  core:
    image: quay.io/aelve/codesearch-core:${TAG:?}
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5h
      update_config:
        failure_action: rollback
    depends_on:
      - postgres
    volumes:
      - /mnt/vol/data:/data
      - /mnt/vol/index:/index
      - /mnt/vol/logs:/logs
    command: >
      sh -c "./wait-for postgres:5432 -- make tables && \
            make download-haskell update-haskell index-haskell && \
            make download-rust update-rust index-rust && \
            make download-ruby update-ruby index-ruby"
    networks:
      - overlay
  server:
    image: quay.io/aelve/codesearch-web-server:${TAG:?}
    deploy:
      mode: global
      restart_policy:
        condition: any
      update_config:
        failure_action: rollback
    volumes:
      - /mnt/vol/data:/data
      - /mnt/vol/index:/index
    depends_on:
      - postgres
    command:
      make serve
    environment:
      LOG_LEVEL: DEBUG
      JAVA_OPTS: "-Dplay.filters.hosts.allowed.1=${SERVER_HOST:?}"
      APPLICATION_SECRET: ${SECRET_KEY:?}
    ports:
      - ${SERVER_PORT:?}:80
    networks:
      - overlay
networks:
  overlay:
