version: '3.3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - /mnt/vol/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sourcesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    ports:
      - 5432:5432
    networks:
      - overlay
  core:
    image: quay.io/aelve/codesearch-core:latest
    depends_on:
      - postgres
    volumes:
      - /mnt/vol/data:/data
      - /mnt/vol/index:/index
      - /mnt/vol/logs:/logs
    command: >
      sh -c "./wait-for postgres:5432 -- make tables && \
            make download-haskell update-haskell index-haskell && \
            make download-rust update-rust index-rust"
    networks:
      - overlay
  server:
    image: quay.io/aelve/codesearch-web-server:latest
    volumes:
      - /mnt/vol/data:/data
      - /mnt/vol/index:/index
    depends_on:
      - postgres
    command:
      make serve
    environment:
      LOG_LEVEL: DEBUG
      JAVA_OPTS: "-Dplay.filters.hosts.allowed.1=codesearch.aelve.com -Dplay.filters.hosts.allowed.2=cloud.digitalocean.com -Dplay.filters.hosts.allowed.3=localhost:9090"
      # In production you must override the APPLICATION_SECRET key
      APPLICATION_SECRET: ${SECRET_KEY:-"u?:IPZT:Cun;SP>edigHDs:cpUf2cY\`<7D>b9lHg98^NsVGn]:eLCIjz1Tt_VyIv"}
    ports:
      # In production you must override SERVER_PORT like: `SERVER_PORT=80 docker-compose -f docker-stack-compose.yml ...`
      - ${SERVER_PORT:-9090}:80
    networks:
      - overlay
networks:
  overlay:
