version: '3'
services:
  web-server:
    container_name: web-server
    build: ./web-server
    ports: 
      - "9000:80"
  core:
    container_name: core
    build: ./core

  postgres:
    image: postgres 
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=sourcesdb 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /Users/yan/Desktop/postshaer:/var/lib/postgresql

