version: '3.3'

services:
  core:
    restart: on-failure
    container_name: codesearch_core
    image: quay.io/aelve/codesearch-core:latest
    external_links:
    - postgres_1
    volumes:
    - /mnt/vol/data:/data
    - /mnt/vol/index:/index
    - /mnt/vol/logs:/logs
    command: >
      sh -c "make tables && \
            make download-haskell update-haskell index-haskell && \
            make download-rust update-rust index-rust && \
            make download-ruby update-ruby index-ruby && \
            make download-javascript update-javascript index-javascript"
    networks:
    - default
    - codesearch_default
networks:
  codesearch_default:
    external: true
