version: '3.3'

services:
  core:
    container_name: core
    restart: on-failure
    image: quay.io/aelve/codesearch-core:develop
    external_links:
      - postgres_db
    volumes:
      - /mnt/vol/data:/data
      - /mnt/vol/index:/index
      - /mnt/vol/logs:/logs
    command: >
      sh -c "make tables && \
            make download-haskell update-haskell index-haskell && \
            make download-rust update-rust index-rust && \
            make download-ruby update-ruby index-ruby && \
            make download-javascript update-javascript index-javascript"
    networks:
      - codesearch_network
networks:
  codesearch_network:
    external: true
